### ISSUE TITLE
Improve cli help information

### ISSUE THREAD

**Issue by Fran-Rg** [Hakky54/certificate-ripper#47]
This is a great tool and I think has been made with the right intent. In my opinion a bit of polishing on the --help would make it easier to use, I had to check couple of example on the README to be able to obtain the required information

```
> crip --help
Unknown option: '--help'
Usage: crip [COMMAND]
CLI tool to extracts server certificates
Commands:
  print   Prints the extracted certificates to the console
  export  Export the extracted certificate to the provided output type
```
-> Not sure why the "--help" is unknown as it's a regular option.
```
> crip print --help
Missing required option: '--url=<urls>'
Usage: crip print [--proxy-password] [--resolve-ca] [-f=<format>]
                  [--proxy-host=<proxyHost>] [--proxy-port=<proxyPort>]
                  [--proxy-user=<proxyUser>] [-t=<timeoutInMilliseconds>]
                  -u=<urls> [-u=<urls>]...
Prints the extracted certificates to the console
  -f, --format=<format>   To be printed certificate format
```
-> the format description should provide the list of available formats.

```
> crip export --help
Unknown option: '--help'
Usage: crip export [COMMAND]
Export the extracted certificate to the provided output type
Commands:
  pkcs12, p12  Export the extracted certificate to a PKCS12/p12 type truststore
  jks          Export the extracted certificate to a JKS (Java KeyStore) type
                 truststore
  der          Export the extracted certificate to a binary form also known as
                 DER
  pem          Export the extracted certificate to a base64 encoded string also
                 known as PEM
```
-> I didn't understand what "COMMAND" refered to since all COMMANDS are actually formats. Can [COMMAND] be replace with [FORMAT]
-> Since the print option has an option "--format" why can't this option also be added? As if format of export isn't specified use the "--format" option

**Comment by Hakky54** [comment]
Hi Fran,

I initially thought of adding a help option, but afterwords I decided that it would not be needed. The main reason was that when an user enters insufficient commands/options or invalid options it will print an error and on the next line it will give you the details of the possible options with a description. But I understand your remark, in a cli app it is common to have a help option. Maybe it is more convenient to just provide a help option without the need for an user entering wrong input to pop up the description.

Most of your concerns can be resolved. I will create a PR and we can continue there. Maybe you can review in on the way while making progress to make this app more friendly by polishing it together, what do you think?

**Comment by Hakky54** [comment]
> the format description should provide the list of available formats.

I added the options in the description for the available formats for printing

<img width="490" alt="Screenshot 2024-12-05 at 22 40 31" src="https://github.com/user-attachments/assets/3b02a88f-4f48-4bc4-8d0c-d6c52b0dd9b4">



> I didn't understand what "COMMAND" refered to since all COMMANDS are actually formats. Can [COMMAND] be replace with [FORMAT]

It actually means a subcommand. I am using a library to simplify the creation of a CLI app and this is the default value. Luckily it is adjustable and I adjusted it. Now it is having format as shown here:

<img width="646" alt="Screenshot 2024-12-05 at 22 43 25" src="https://github.com/user-attachments/assets/634c499b-1c85-433f-9314-9c66ee39c707">

> Since the print option has an option "--format" why can't this option also be added? As if format of export isn't specified use the "--format" option

I know it is a bit confusing. I also didn't prefer to have it like that. However the export commands needs different arguments depending on the format, such as p12 or jks needs a keystore password, der files don't need that and pem files can be combined into a single file. I needed to use subcommand instead of command options to make these options possible for different formats and to have the validations on those option. The downside is that it is not consistent with the print option.

So I understand your remarkt but I could not make it working in the code and therefore I decided to have the current setup with subcommands.

The PR is here https://github.com/Hakky54/certificate-ripper/pull/48 , please have a look at it and if you have other improvements please go ahead and share your thoughts

**Comment by Fran-Rg** [comment]
Looks good. All make sense

**Comment by Hakky54** [comment]
There was a disucssion in the past in the cummunity regarding master term for the base branch whether it is related to racisms. I understand the concerns, but I don't feel it is related to slavery or racism so I am ok with the master branch in existing projects. In new repo's I consider using main as base branch. So for this repo I prefer to keep it as is

**Comment by Hakky54** [comment]
Hi mate, just wanted to give an update on these changes. I will publish a new version in the beginning of January. I want to include some changes from here: https://github.com/Hakky54/sslcontext-kickstart
